name: Deploy to Cloud Run
on: [push]

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
        service_account: ${{ secrets.GCP_WIF_SERVICE_ACCOUNT }}

    - uses: google-github-actions/setup-gcloud@v2

    - name: Set GCP Project
      run: gcloud config set project ${{ secrets.GCP_PROJECT }}

    - name: Debug Secrets
      run: |
        echo "GCP_PROJECT: ${{ secrets.GCP_PROJECT }}"
        echo "GCP_WIF_SERVICE_ACCOUNT: ${{ secrets.GCP_WIF_SERVICE_ACCOUNT }}"
        echo "GCP_WIF_PROVIDER (last 50 chars): ...$(echo '${{ secrets.GCP_WIF_PROVIDER }}' | tail -c 50)"

    - name: Deploy
      run: |
        gcloud run deploy python-app \
          --region=asia-northeast1 \
          --source=. \
          --service-account=app-runtime@${{ secrets.GCP_PROJECT }}.iam.gserviceaccount.com \
          --set-env-vars="SLACK_BOT_TOKEN=$(gcloud secrets versions access latest --secret=slack-bot-token),SLACK_SIGNING_SECRET=$(gcloud secrets versions access latest --secret=slack-signing-secret),GEMINI_API_KEY=$(gcloud secrets versions access latest --secret=gemini-api-key),GEMINI_MODEL_NAME=$(gcloud secrets versions access latest --secret=gemini-model-name),SOCKET_MODE=false,STORAGE_BACKEND=$(gcloud secrets versions access latest --secret=storage-backend),LOG_LEVEL=$(gcloud secrets versions access latest --secret=log-level)" \
          --port=8080 \
          --min-instances=0 \
          --max-instances=10 \
          --allow-unauthenticated
