name: Deploy to Cloud Run
on: [push]

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
        service_account: ${{ secrets.GCP_WIF_SERVICE_ACCOUNT }}

    - uses: google-github-actions/setup-gcloud@v2

    - name: Set GCP Project
      run: gcloud config set project ${{ secrets.GCP_PROJECT }}

    - name: Deploy
      run: |
        gcloud run deploy python-app \
          --region=asia-northeast1 \
          --source=. \
          --service-account=app-runtime@${{ secrets.GCP_PROJECT }}.iam.gserviceaccount.com \
          --set-secrets="SLACK_BOT_TOKEN=slack-bot-token:latest,SLACK_SIGNING_SECRET=slack-signing-secret:latest,GEMINI_API_KEY=gemini-api-key:latest,GEMINI_MODEL_NAME=gemini-model-name:latest,STORAGE_BACKEND=storage-backend:latest,LOG_LEVEL=log-level:latest" \
          --set-env-vars="SOCKET_MODE=false" \
          --port=8080 \
          --min-instances=0 \
          --max-instances=10 \
          --allow-unauthenticated
